apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app
  namespace: myapp
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./app
  prune: true
  validation: client

