apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hlpod
    herve: washere
  name: hlpod
  namespace: myapp
spec:
  containers:
  - image: nginx
    name: hlpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
